openapi: 3.0.0
info:
  title: Templio API
  version: '1.0'
servers:
  - url: 'https://api.templioapp.com'
paths:
  /render:
    post:
      summary: ''
      operationId: post-render
      responses:
        '200':
          description: OK
    get:
      operationId: ''
components:
  schemas: {}
